name: reusable-ruby-gem-release-pr

on:
  workflow_call:
    inputs:
      target_branch:
        required: false
        type: string
        default: main

permissions:
  contents: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ inputs.target_branch }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
